"""The mechanical part model, view engine and standards tables.

Merge rule for the four track-B/G branches: the re-exports below are additive
and alphabetical — keep every side's names.
"""

from __future__ import annotations

from .features import (
    FEATURE_KINDS,
    AxialBore,
    BendLine,
    CentreHole,
    Chamfer,
    CornerChamfer,
    CornerFillet,
    CrossHole,
    Feature,
    Fillet,
    GearTeeth,
    Hole,
    HoleCircle,
    HolePattern,
    Keyway,
    ORingGroove,
    Pocket,
    RetainingGroove,
    Slot,
    Thread,
    Undercut,
    feature_from_dict,
    mirror_about_x,
)
from .part import (
    PART_KINDS,
    PrismaticPart,
    RevolvedPart,
    Segment,
    build_part,
    inner_radius_at,
    outer_radius_at,
    outline_bbox,
    part_length,
    part_max_diameter,
    part_to_dict,
    point_in_outline,
    segment_bounds,
    validate_part,
)
from .primitives import (
    ROLE_LAYER,
    ROLES,
    Arc,
    Circle,
    DimIntent,
    HatchArea,
    Line,
    Poly,
    Prim,
    Pt,
    Role,
    Text,
    bbox,
    layer_for,
    points_of,
    rotate,
    scale,
    translate,
)

__all__ = [
    "FEATURE_KINDS",
    "PART_KINDS",
    "ROLES",
    "ROLE_LAYER",
    "Arc",
    "AxialBore",
    "BendLine",
    "CentreHole",
    "Chamfer",
    "Circle",
    "CornerChamfer",
    "CornerFillet",
    "CrossHole",
    "DimIntent",
    "Feature",
    "Fillet",
    "GearTeeth",
    "HatchArea",
    "Hole",
    "HoleCircle",
    "HolePattern",
    "Keyway",
    "Line",
    "ORingGroove",
    "Pocket",
    "Poly",
    "Prim",
    "PrismaticPart",
    "Pt",
    "RetainingGroove",
    "RevolvedPart",
    "Role",
    "Segment",
    "Slot",
    "Text",
    "Thread",
    "Undercut",
    "bbox",
    "build_part",
    "feature_from_dict",
    "inner_radius_at",
    "layer_for",
    "mirror_about_x",
    "outer_radius_at",
    "outline_bbox",
    "part_length",
    "part_max_diameter",
    "part_to_dict",
    "point_in_outline",
    "points_of",
    "rotate",
    "scale",
    "segment_bounds",
    "translate",
    "validate_part",
]
